### ISSUE TITLE
What's the difference

### ISSUE THREAD

**Issue by 649459021** [primepake/wav2lip_288x288#1]
Hi, thanks for this work.
May I ask the difference between this work and wav2lip except the network structure?

**Comment by primepake** [comment]
here is the version where you can train the model with 1080p and i fixed some activation function so the model can be more efficient

**Comment by primepake** [comment]
you can read this issues to learn more
https://github.com/Rudrabha/Wav2Lip/issues/107

**Comment by primepake** [comment]
because the output of author 96x96 and resize by opencv. So if your original face in your bigger than 96x96 and then 96x96 model will not work well

**Comment by primepake** [comment]
I will add Wasserstein and gradient penalty for the loss function soon

**Comment by 649459021** [comment]
Thanks for your reply. 
So let me summarize:
   1. ReLU -> PReLU
   2. Gradient penalty
   3. Wasserstein
   4. Input size: 96 -> 288
Is there anything I missed ？

**Comment by 649459021** [comment]
By the way, how many steps can sync_loss be lower than 0.75?

**Comment by primepake** [comment]
after 2k iter it can get lower 0.75. My dataset is private (1080p, no noise, The expression of the speaker is very normal, not too expressive) bs 128, 4 gpus tesla p100

**Comment by 649459021** [comment]
Thanks!  
I can't get lower than 0.75 in LRS2 dataset.

**Comment by NikitaKononov** [comment]
> 

Hello! Can you please tell us, when do you plan to implement Wasserstein loss and gradient penalty? Thanks!
