### ISSUE TITLE
the loss is stuck at around 0.69 during training the syncnet

### ISSUE THREAD

**Issue by Rodger-Huang** [primepake/wav2lip_288x288#11]
When I used the dataset collected by myself to train the syncnet of wav2lip, the loss tended to be around 0.69. Have you ever had the same problem? Hope you can help me. Thanks!

**Comment by primepake** [comment]
yes, I've encountered this problem. You should download avspecch dataset to discover the structure.
But I'll suggest for you some tips:
1. your dataset needs to be various (multiple speakers)
2.  max length of the video is 10s (a speaker has multiple videos)
3. change fps of video to 25fps

**Comment by aishoot** [comment]
@Rodger-Huang Have you solved this problem? I met it, too.
