### ISSUE TITLE
Access troubles on Linux

### ISSUE THREAD

**Issue by NikitaKononov** [primepake/wav2lip_288x288#12]
Hello, what OS have you used while working with this project? 
All works fine on Windows, but on linux I have some troubles: hparams.py doesn't see filelists (but they exist in the right directory) and etc. 
With original Wav2Lip repo all works fine on both OS.
I think there is some problem with file(s)/directory(ies) from repo: access, rights, owners or attributes. Did you set any special attributes or parameters on files/directories in your project? 
Thanks

**Comment by primepake** [comment]
you need to create file filelists by your own
or you can try this code
```
import os
import json, subprocess, random, string
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--data_root', help='dataset path', default='./videos', type=str)
args = parser.parse_args()

def createFileList(dataset_path):
  with open('filelists/train.txt', 'w') as train, open('filelists/test.txt', 'w') as test, open('filelists/val.txt', 'w') as vald:
    identities = os.listdir(dataset_path)
    for identity in identities:
      videos = os.listdir(os.path.join(dataset_path, identity))
      # numOfTest = len(videos)//6 + len(videos)%2 + 1
      # training, testing = videos[:-numOfTest], videos[-numOfTest:]
      # testing, validation = testing[:len(testing)//2], testing[len(testing)//2:]
      training = videos
      testing = videos
      validation = videos
      print(f'{identity}: training-{len(training)}, testing-{len(testing)}, validation-{len(validation)}')
      for video in training:
        train.write(f"{identity}/{video.split('.')[0]}\n")
      for video in testing:
        test.write(f"{identity}/{video.split('.')[0]}\n")
      for video in validation:
        vald.write(f"{identity}/{video.split('.')[0]}\n")
createFileList(f'{args.data_root}')
```

**Comment by prometheus-alien** [comment]
> you need to create file filelists by your own or you can try this code
> 
> ```
> import os
> import json, subprocess, random, string
> import argparse
> 
> parser = argparse.ArgumentParser()
> parser.add_argument('--data_root', help='dataset path', default='./videos', type=str)
> args = parser.parse_args()
> 
> def createFileList(dataset_path):
>   with open('filelists/train.txt', 'w') as train, open('filelists/test.txt', 'w') as test, open('filelists/val.txt', 'w') as vald:
>     identities = os.listdir(dataset_path)
>     for identity in identities:
>       videos = os.listdir(os.path.join(dataset_path, identity))
>       # numOfTest = len(videos)//6 + len(videos)%2 + 1
>       # training, testing = videos[:-numOfTest], videos[-numOfTest:]
>       # testing, validation = testing[:len(testing)//2], testing[len(testing)//2:]
>       training = videos
>       testing = videos
>       validation = videos
>       print(f'{identity}: training-{len(training)}, testing-{len(testing)}, validation-{len(validation)}')
>       for video in training:
>         train.write(f"{identity}/{video.split('.')[0]}\n")
>       for video in testing:
>         test.write(f"{identity}/{video.split('.')[0]}\n")
>       for video in validation:
>         vald.write(f"{identity}/{video.split('.')[0]}\n")
> createFileList(f'{args.data_root}')
> ```

谢谢 好人一生平安

**Comment by einsqing** [comment]
> you need to create file filelists by your own or you can try this code
> 
> ```
> import os
> import json, subprocess, random, string
> import argparse
> 
> parser = argparse.ArgumentParser()
> parser.add_argument('--data_root', help='dataset path', default='./videos', type=str)
> args = parser.parse_args()
> 
> def createFileList(dataset_path):
>   with open('filelists/train.txt', 'w') as train, open('filelists/test.txt', 'w') as test, open('filelists/val.txt', 'w') as vald:
>     identities = os.listdir(dataset_path)
>     for identity in identities:
>       videos = os.listdir(os.path.join(dataset_path, identity))
>       # numOfTest = len(videos)//6 + len(videos)%2 + 1
>       # training, testing = videos[:-numOfTest], videos[-numOfTest:]
>       # testing, validation = testing[:len(testing)//2], testing[len(testing)//2:]
>       training = videos
>       testing = videos
>       validation = videos
>       print(f'{identity}: training-{len(training)}, testing-{len(testing)}, validation-{len(validation)}')
>       for video in training:
>         train.write(f"{identity}/{video.split('.')[0]}\n")
>       for video in testing:
>         test.write(f"{identity}/{video.split('.')[0]}\n")
>       for video in validation:
>         vald.write(f"{identity}/{video.split('.')[0]}\n")
> createFileList(f'{args.data_root}')
> ```

Is the data in the training and validation sets the same?
