### ISSUE TITLE
老哥，你为嘛把项目名称改来改去？

### ISSUE THREAD

**Issue by prometheus-alien** [primepake/wav2lip_288x288#123]
如题。
顺便感谢作者的开源，好人一生平安~

**Comment by tailangjun** [comment]
> 如题。 顺便感谢作者的开源，好人一生平安~

老哥估计看不懂中文，哈哈

**Comment by tailangjun** [comment]
我觉得名字改成Wav2Lip++会更合适 😄

**Comment by primepake** [comment]
I just changed it to the started name

**Comment by prometheus-alien** [comment]
> > 如题。 顺便感谢作者的开源，好人一生平安~
> 
> 老哥估计看不懂中文，哈哈

本意是想开个玩笑，打算自己关闭的，搞别的去了忘了😓

**Comment by Nyquist0** [comment]
I would like to vote to **wav2lip_enhanced**. Some enhancements of this project really make sense!
