### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by ntakouris** [primepake/wav2lip_288x288#125]
Hi @primepake ,

Can you add a license to this? Legally, without one, the code is like a "museum" piece. You can only look at this and not use it for research, or commercial use.

The simplest one to do would be the [MIT License](https://choosealicense.com/licenses/mit). Those are typically added as a `LICENSE` plaintext file at the root of the repository.

**Comment by ntakouris** [comment]
If you can do this for the "original" repository as well mentioned in the README, it would be very, very useful.

**Comment by primepake** [comment]
done!

**Comment by ntakouris** [comment]
TY
