### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by see2run** [primepake/wav2lip_288x288#141]
Hello, can anyone help me?

I'm processing a dataset using preprocess.py and listing its subfolders into a txt file.

Then, the output that appears is only:

use_cuda: True
total trainable params 65054464
Training From Scratch !!!
Starting Epoch: 0
True

for the True output there I'm trying to make sure of the dataloader with
if train_data_loader:
print(True)
else:
print(False)

**Comment by see2run** [comment]
Because after I checked, this loop process isn't running but also not showing any errors:

for step, (x, mel, y) in enumerate(train_data_loader):
st = time()
print("running")
model.train()
optimizer.zero_grad()

where the print("running") is not displayed

**Comment by see2run** [comment]
update:

i increase my dataset, and now

use_cuda: True
total trainable params 65054464
Training From Scratch !!!
Starting Epoch: 0
True

but, still stuck, and no progress

**Comment by LinYi-JCY** [comment]
Have you solved the problem?

**Comment by see2run** [comment]
> Have you solved the problem?

yeah

**Comment by LinYi-JCY** [comment]
Can you provide some solutions? I also encountered this problem, thank you very much!🙏

**Comment by see2run** [comment]
> Can you provide some solutions? I also encountered this problem, thank you very much!🙏

What I did was just fix the train syncnet and wav2lip scripts in the Dataset class. Pay attention to whether the path for obtaining the list file is correct and find out if there is any variable with a None value in that class. Then, at the very least, use more than 1000 training data and more than 100 test data (if you want to test whether the script works or not). If there is anything else you want to ask, feel free to ask

**Comment by LinYi-JCY** [comment]
> What I did was just fix the train syncnet and wav2lip scripts in the Dataset class. Pay attention to whether the path for obtaining the list file is correct and find out if there is any variable with a None value in that class. Then, at the very least, use more than 1000 training data and more than 100 test data (if you want to test whether the script works or not). If there is anything else you want to ask, feel free to ask

Ok, I will try this solution. Thank you again!
