### ISSUE TITLE
color_syncnet_train.py

### ISSUE THREAD

**Issue by Quanta-of-solitude** [primepake/wav2lip_288x288#16]
So, I have preprocessed a part of the AVSpeech dataset and ran the command for color_syncnet_train.py. The filelists (train.txt, and val.txt) are properly done as well but the output  is like this:

python color_syncnet_train.py --data_root preprocess --checkpoint_dir checkpoints/
use_cuda: True
total trainable params 19881059
0it [00:00, ?it/s]Saved checkpoint: checkpoints/checkpoint_step000000001.pth
Loss: 1.0145502090454102: : 1it [16:59, 1019.31s/it]
0it [00:00, ?it/s]

Is this going on fine? why is it going for 1 it? 
There are around 49 entries in train.txt and 26 in val.txt (all of them preprocessed). The folder paths look fine to me as well, not sure what am I messing up.

**Comment by primepake** [comment]
you need to collect more dataset and preprocessing them

**Comment by Quanta-of-solitude** [comment]
Alright, but now I am getting an error after running this for sometime:

python color_syncnet_train.py --data_root preprocessedData/ --checkpoint_dir checkpoints

use_cuda: True
total trainable params 19881059
0it [00:00, ?it/s]Saved checkpoint: checkpoints/checkpoint_step000000001.pth
Loss: 1.130293607711792: : 1it [12:44, 764.86s/it]
Loss: 0.9026422500610352: : 1it [14:37, 877.93s/it]
Loss: 1.0647838115692139: : 1it [14:40, 880.54s/it]
Loss: 1.0123388767242432: : 1it [15:36, 936.53s/it]
Loss: 0.9266862869262695: : 1it [15:00, 900.80s/it]
Loss: 0.8942291140556335: : 1it [13:57, 837.86s/it]
Loss: 1.0073713064193726: : 1it [15:19, 919.58s/it]
Loss: 1.0768300294876099: : 1it [15:41, 941.04s/it]
Loss: 0.9291326999664307: : 1it [16:07, 967.90s/it]
Loss: 0.9046692848205566: : 1it [13:43, 823.88s/it]
Loss: 0.6578884720802307: : 1it [16:10, 970.35s/it]
Loss: 1.1847789287567139: : 1it [12:44, 764.03s/it]
Loss: 1.0758931636810303: : 1it [12:53, 773.66s/it]
Loss: 0.9432123899459839: : 1it [13:43, 823.22s/it]
Loss: 1.0592972040176392: : 1it [14:08, 848.07s/it]
Loss: 0.8582468032836914: : 1it [16:44, 1004.22s/it]
Loss: 0.9379435777664185: : 1it [14:03, 843.51s/it]

0it [00:00, ?it/s]/pytorch/aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [0,0,0], thread: [37,0,0] Assertion input_val >= zero && input_val <= one failed.
0it [16:28, ?it/s]
Traceback (most recent call last):
File "color_syncnet_train.py", line 279, in
nepochs=hparams.nepochs)
File "color_syncnet_train.py", line 162, in train
loss.backward()
File "/home/Wav2Lip/env/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/home/Wav2Lip/env/lib/python3.6/site-packages/torch/autograd/init.py", line 156, in backward
allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Quanta-of-solitude** [comment]
changing BCE Loss, to BCE Loss with logita solved the issue

**Comment by Quanta-of-solitude** [comment]
I have been running this script for 2 days now, but the checkpoint hasnt updated since the first named: checkpoint_step000000001.pth

**Comment by primepake** [comment]
you need to check your code, how many epochs your code will automatically save the model?

**Comment by hannarud** [comment]
Hi @Quanta-of-solitude! Did you resolve the problem with no checkpoint being saved? I'm running the training for 15 hours now and only the `checkpoint_step000000001.pth` was saved. Loss is going down, but very slow (started from 0.8 now it is 0.68). I changed the loss function to `nn.BCEWithLogitsLoss()`

**Comment by primepake** [comment]
don't use bcewithlogit, I need to understand fully about this function. It maybe have effect your training

**Comment by hannarud** [comment]
Hi @primepake! Okay, I suspected that, but if not using it, I'm getting negative values on `loss.backward()` call. You actually advised to use it in https://github.com/primepake/wav2lip_288x288/issues/13 - I wonder how you trained the `color_syncnet_train.py` otherwise?

**Comment by Quanta-of-solitude** [comment]
@hannarud I wasn't able to solve it...

**Comment by hannarud** [comment]
Hi @Quanta-of-solitude! I actually solved that! First, in `hparams.py` it is set that the checkpoint is saved every `10000` steps (`syncnet_checkpoint_interval` parameter), so you can set the checkpoint to be saved more often. Next, BCEwithLogits was necessary because for some reason PReLU was set as activation in Conv2D, need to change it back to ReLU.
But even I did it all I'm still not able to train the model =) the loss is either stuck at 0.69 or model starts to overfit (training loss drops up to 0.4, but val is at 0.8-1.1)

**Comment by davidmartinrius** [comment]
> Hi @Quanta-of-solitude! I actually solved that! First, in `hparams.py` it is set that the checkpoint is saved every `10000` steps (`syncnet_checkpoint_interval` parameter), so you can set the checkpoint to be saved more often. Next, BCEwithLogits was necessary because for some reason PReLU was set as activation in Conv2D, need to change it back to ReLU. But even I did it all I'm still not able to train the model =) the loss is either stuck at 0.69 or model starts to overfit (training loss drops up to 0.4, but val is at 0.8-1.1)

Hello @hannarud . Finally, did you find out how to train the model successfully?
Please, if you know how to solve it, could you share how to fix it?
Thank you!
