### ISSUE TITLE
Sample outputs

### ISSUE THREAD

**Issue by NikitaKononov** [primepake/wav2lip_288x288#17]
Hello!
Can you please share some samples of your model inference? 
Any videos with your high quality 288x288px lip sync
I just want to find out, is the training of HQ Wav2Lip is reasonable
Thanks

(not the model, only samples of it's work)

**Comment by NikitaKononov** [comment]
> sorry, i can't share but you can see the issue: [#10 (comment)](https://github.com/primepake/wav2lip_288x288/issues/10#issuecomment-1084105389)

Do the results in this issue have the same visual quality as your model? Or you have a way better result?
Why you can't btw?

**Comment by primepake** [comment]
sorry because I left the organization, this is my commitment. This is nearly my result

**Comment by NikitaKononov** [comment]
> sorry because I left the organization, this is my commitment. This is nearly my result

Understood, thanks
Hm.. Result is not very impressive to be honest, much artefacts
Do you know any modern models for lip-sync or talking head generation?
I've tried FACIAL, but it's blinking quality and overall visual quality isn't very good

**Comment by primepake** [comment]
you can contact the author wav2lip to see the result 288x192, this result is very good. But this implementation has a lot of implementation. because it just gets 5 frames and I saw it doesn't has any connection from the previous step to the next step. So I think you need to implement better model through LSTM or RNN or something can make connection

**Comment by NikitaKononov** [comment]
> you can contact the author wav2lip to see the result 288x192, this result is very good. But this implementation has a lot of limitation. because it just gets 5 frames and I saw it doesn't has any connection from the previous step to the next step. So I think you need to implement better model through LSTM or RNN or something can make connection

https://iiitaphyd-my.sharepoint.com/personal/radrabha_m_research_iiit_ac_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fradrabha_m_research_iiit_ac_in%2FDocuments%2FWav2Lip_results%2FSravan%2FSravan_Telugu_720p%2Emp4&parent=%2Fpersonal%2Fradrabha_m_research_iiit_ac_in%2FDocuments%2FWav2Lip_results%2FSravan&ga=1

Their 288x192 result
Can't call it very good, especially for the price of 7500$

**Comment by cmmclee** [comment]
Hello @NikitaKononov This video address cannot be accessed. Can you upload this video file?  Thanks

**Comment by NikitaKononov** [comment]
> Hello @NikitaKononov This video address cannot be accessed. Can you upload this video file? Thanks

https://user-images.githubusercontent.com/69078939/186162660-6afe6330-bd1f-44e7-97d9-ed1afb3c928f.mp4

**Comment by cmmclee** [comment]
Thanks for your quick response

**Comment by primepake** [comment]
My method can get better result but I can take a lot of resources gpu

**Comment by NikitaKononov** [comment]
> My method can get better result but I can take a lot of resources gpu
Alot of resources while training? or while inference
will you shade your method?

**Comment by primepake** [comment]
I mean this repo
