### ISSUE TITLE
share video demos

### ISSUE THREAD

**Issue by cmmclee** [primepake/wav2lip_288x288#2]
Hi, thanks for this work
Can you share some Lip-sync video results of your work?  
thanks

**Comment by primepake** [comment]
I'm sorry, our dataset is private

**Comment by MAYBreath** [comment]
share any video demo,not your private dataset

**Comment by primepake** [comment]
https://studenthcmusedu-my.sharepoint.com/:v:/g/personal/1511261_student_hcmus_edu_vn/ESqmfYMbMU5CpfJZWskgSIEBnk1fWyGC0Y7JHcsVFS1jOA?e=Z32yvf. You can see here
