### ISSUE TITLE
How to train with custom datset ?

### ISSUE THREAD

**Issue by Unmesh28** [primepake/wav2lip_288x288#21]
Hi,  I am quiet new to this. I am looking for step by step guide to train custom dataset OR Train on AVSpeech dataset and finetune for other videos. Steps can be : 
- Download the dataset 
- Clean and convert to 25fps [If 30fps what should be done] 
- Train
- Finetune on custom videos 
- Test

I think such guide will help a lot of people not get confused.

Thank You.

**Comment by primepake** [comment]
- download dataset
- detect faces
- convert 25fps
- using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1]
- train expert_syncnet with evaluation loss < 0.25 then you can stop your training
- train wav2lip model

**Comment by Unmesh28** [comment]
@primepake Thanks. 

But I was looking for the codes to run for each step with directory structure and other related info required.

**Comment by primepake** [comment]
you should process your dataset carefully, It will effect your training

**Comment by Unmesh28** [comment]
Yeah, thats why looking for a step by step guide from you. It would really help me. Can you provide a doc or readme or something ? So that anybody can just follow the steps and start training. I have gone through and done training using the 96*96 wav2lip repo, but looking for more res results.

**Comment by Donggeon** [comment]
Hi @primepake , Thanks for your comments.
Could you let me know the location of ' syncnet_python ' file to filter out the dataset?

**Comment by Unmesh28** [comment]
@Donggeon I think he meant "color_syncnet_train.py" this file.

If you have figured out previous steps can u tell me what u did exactly ?

**Comment by Donggeon** [comment]
> https://github.com/joonson/syncnet_python you can use this repo

Thanks for your answering. I was wondering if you could give me some more detailed instructions.
Because we detected faces using preprocessing code in wav2lip, it seems that we only need to check sync using some functions of syncnet python code.

**Comment by Unmesh28** [comment]
@primepake Can you please share detailed instructions for training ?

**Comment by primepake** [comment]
I will release the code, it's a ton of code

**Comment by Donggeon** [comment]
Thanks @primepake, it'd be a great help.

**Comment by Unmesh28** [comment]
> I will release the code, it's a ton of code

Thanks 👍🏻

**Comment by skyler14** [comment]
do you also have your checkpoint from the avspeech runs, prior to running on your private dataset? I'm interested in comparing how it turns out vs training via the instructions you provide.

**Comment by primepake** [comment]
I won't public pretrained, but you can trust model implementation.
this is my demo: https://drive.google.com/file/d/1H6AVcI1V9j9OBv6YdxVmB_6wVy5PcpCh/view?usp=sharing

**Comment by primepake** [comment]
I will public pretrained on avspeech

**Comment by skyler14** [comment]
Great, thank you. Can you also leave an estimate of the gpu hardware and compute time it took for you to do the checkpoint training and finetuning.

**Comment by primepake** [comment]
I used 10 GPU A6000 with nearly 200GB memory of GPU

**Comment by primepake** [comment]
the trial and error just in a day

**Comment by skyler14** [comment]
ok, great. For the public avspeech pretrained checkpoint is it being put in the repo, as a link in the readme, or just here in the issues?

**Comment by Unmesh28** [comment]
@Unmesh28 When can you upload detailed training instructions for preprocessing ?

**Comment by crazyxprogrammer** [comment]
Can you please detailed instructions for https://github.com/joonson/syncnet_python. How to use this repo.

**Comment by sylvie-lauf** [comment]
> * download dataset
> * detect faces
> * convert 25fps
> * using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1]
> * train expert_syncnet with evaluation loss < 0.25 then you can stop your training
> * train wav2lip model

Is this the correct order ?

**Comment by primepake** [comment]
> 

yes

**Comment by skyler14** [comment]
Any update on the avspeech only checkpoint?

**Comment by primepake** [comment]
> 

hi, I updated my preprocessing step, sorry about missing ordering

**Comment by skyler14** [comment]
How many videos did you need per the method you wrote for the fine-tuning step?

**Comment by crazyxprogrammer** [comment]
can you give more details about this 4th step (split video less than 5s.). Is this step included in clean_data.py. And in the fifth step (using syncnet_python to filter dataset in the range [-3, 3]) should I have to only filter on the basis of offset given by Syncnet_python or Should I have to correct Synchronization.

**Comment by Unmesh28** [comment]
> * download dataset
> * convert to 25fps.
> * change sample rate to 16000hz.
> * split video less than 5s.
> * using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1].
> * detect faces.
> * train expert_syncnet with evaluation loss < 0.25 then you can stop your training
> * train wav2lip model

@primepake what do you mean by "split video less than 5s". Does it mean split longer videos in smaller videos with duration less than 5 sec ?

**Comment by primepake** [comment]
> 

lip-sync expert has many problems, you need to find it. As the author mentioned, it doesn't care about similarity between frames. You need to read the paper to understand more.

Does not reflect the real-world usage. As discussed before,
during generation at test time, the model must not change the pose,
as the generated face needs to be seamlessly pasted into the frame.
However, the current evaluation framework feeds random reference
frames in the input, thus demanding the network to change the
pose. Thus, the above system does not evaluate how the model
would be used in the real world.

**Comment by sylvie-lauf** [comment]
@primepake I want to buy your model. Can you please share details on : sylvie.nexus11@gmail.com

**Comment by skyler14** [comment]
> How many videos did you need per the method you wrote for the fine-tuning step?

just was wondering if I could get this estimate for the fine-tuning after AVspeech (videos and/or minutes of footage)

Also any updates on the AVspeech checkpoint?

**Comment by Unmesh28** [comment]
When I am running syncnet python getting below error :

`WARNING: Audio (3.6720s) and video (3.7200s) lengths are different.
Traceback (most recent call last):
  File "run_syncnet.py", line 40, in <module>
    offset, conf, dist = s.evaluate(opt,videofile=fname)
  File "/home/ubuntu/wav2lip_288x288/syncnet_python/SyncNetInstance.py", line 112, in evaluate
    im_out  = self.__S__.forward_lip(im_in.cuda());
  File "/home/ubuntu/wav2lip_288x288/syncnet_python/SyncNetModel.py", line 108, in forward_lip
    out = self.netfclip(mid);
  File "/home/ubuntu/anaconda3/envs/wav2lip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/wav2lip/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/wav2lip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/wav2lip/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x278528 and 512x512)
`

Does anybody know how to resolve this ?

**Comment by skyler14** [comment]
@primepake thanks for the note about fine-tuning ,do you have any updates on:
Roughly how many videos, GPU hardware, and compute time it took to do the AVSpeech only training
Status of adding the AVSpeech checkpoint


Also I was wondering if fine-tuning generally needed to be done on a per person basis or your propreity data was just alot of people all as one fine-tuned model?

**Comment by primepake** [comment]
this is the problem in your code, you have to figure it out yourself. Just take a screenshot and leave it here so we can't solve it. thank you

**Comment by Unmesh28** [comment]
I am using your exact code, haven't changed it

**Comment by primepake** [comment]
did you change size input in inference file?
![image](https://user-images.githubusercontent.com/39094983/185881222-7f629291-8730-43dd-978e-485abac4d463.png)

**Comment by Unmesh28** [comment]
No, I did not change it. Have kept it as it is.

The only thing I tried changing is `img_size = 288` in hparams.py 
I tried changing it to 192 when suggested by you , but getting same error for 288 and 192.

**Comment by aishoot** [comment]
> * download dataset
> * convert to 25fps.
> * change sample rate to 16000hz.
> * split video less than 5s.
> * using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1].
> * detect faces.
> * train expert_syncnet with evaluation loss < 0.25 then you can stop your training
> * train wav2lip model

Thanks for your nice work. I want to ask why “split video less than 5s”? What effect does it have on the results? I split videos maximum of 20s, is that ok?

**Comment by primepake** [comment]
> > * download dataset
> > * convert to 25fps.
> > * change sample rate to 16000hz.
> > * split video less than 5s.
> > * using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1].
> > * detect faces.
> > * train expert_syncnet with evaluation loss < 0.25 then you can stop your training
> > * train wav2lip model
> 
> Thanks for your nice work. I want to ask why “split video less than 5s”? What effect does it have on the results? I split videos maximum of 20s, is that ok?

To understand more, you should read the paper but if the length of video is too long, it can lead to duplicate sound in this video so the positive pair and negative can be the same in a high probability

**Comment by aishoot** [comment]
> 

Thanks

**Comment by wllps1988315** [comment]
> * download dataset
> * convert to 25fps.
> * change sample rate to 16000hz.
> * split video less than 5s.
> * using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1].
> * detect faces.
> * train expert_syncnet with evaluation loss < 0.25 then you can stop your training
> * train wav2lip model

what syncnet_python stands for?

**Comment by wllps1988315** [comment]
> I used 10 GPU A6000 with nearly 200GB memory of GPU

how long have you trained expert_syncnet and wav2lip using AVspeech?

**Comment by ldz666666** [comment]
> * download dataset
> * convert to 25fps.
> * change sample rate to 16000hz.
> * split video less than 5s.
> * using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1].
> * detect faces.
> * train expert_syncnet with evaluation loss < 0.25 then you can stop your training
> * train wav2lip model

Hi, why we need to split video less than 5s to train the syncnet ?

**Comment by easonhyx** [comment]
> I will public pretrained on avspeech
Dear author, may I ask if the model pre-trained on the AVSpeech dataset can be made public?If there is a plan to make it public, may I ask when it will be available?

**Comment by 1129571** [comment]
> * download dataset
> * convert to 25fps.
> * change sample rate to 16000hz.
> * split video less than 5s.
> * using syncnet_python to filter dataset in range [-3, 3], model works best with [-1,1].
> * detect faces.
> * train expert_syncnet with evaluation loss < 0.25 then you can stop your training
> * train wav2lip model

Hello, I would like to know if the filter dataset in range [-3, 3] you mentioned here refers to offset, conf, or dist in the syncnet_python project?
My current understanding is that:

1. Offset in [-3, 3]

1. Confidence in [6, 9]

Is my understanding correct?
