### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by EhsanRusta** [primepake/wav2lip_288x288#24]
Hello @primepake, pls help me with dataset correction,
on my dataset FPS=30 and need to changed it to 25, up to now I did the face detection and the preprocessed data is frames and audio, what should I do to change FPS?
thank you

**Comment by primepake** [comment]
I need to convert it to 25 fps before detecting faces

**Comment by EhsanRusta** [comment]
and what about if I want proceed with 30 fps?

**Comment by primepake** [comment]
this fps will effect your model, you need to scale up model and change hyper paramertes: syncnet_T,  syncnet_mel_step_size
you need to change the hyper-parameters correctly with 0.2 seconds

**Comment by EhsanRusta** [comment]
also my data sample_rate of audio is 44100 and not 16000, should I change any hyper parameters?

**Comment by primepake** [comment]
read https://github.com/primepake/wav2lip_288x288/issues/21#issuecomment-1172847918

**Comment by EhsanRusta** [comment]
thanks i will change both fps and sample rate
and also Im facing this error for syncnet, did you experienced this? 
![error](https://user-images.githubusercontent.com/87355823/181180186-0a30a0e7-8360-4ee4-8249-b9a1f8ecd6f0.png)
