### ISSUE TITLE
can you shared pretrained_weight of AVspeech?

### ISSUE THREAD

**Issue by boreas-l** [primepake/wav2lip_288x288#25]
thanks for you so nice work!  
I try to use wav2lip_288x288 in my own dataset, but my dataset is small. so I need to use a large dataset(eg. AVSpeech dataset) to do pretrain. But it has to be said that, this training was a large cost in time and compute source.  
so, can you shared your pretrained weight? thankyou.

**Comment by NikitaKononov** [comment]
> thanks for you so nice work! I try to use wav2lip_288x288 in my own dataset, but my dataset is small. so I need to use a large dataset(eg. AVSpeech dataset) to do pretrain. But it has to be said that, this training was a large cost in time and compute source. so, can you shared your pretrained weight? thankyou.

When you ask for them for free - you devalue the work of the Author and showing disrespect to him

**Comment by skyler14** [comment]
> > thanks for you so nice work! I try to use wav2lip_288x288 in my own dataset, but my dataset is small. so I need to use a large dataset(eg. AVSpeech dataset) to do pretrain. But it has to be said that, this training was a large cost in time and compute source. so, can you shared your pretrained weight? thankyou.
> 
> When you ask for them for free - you devalue the work of the Author and showing disrespect to him

This type of commentary is completely off-base for a githubs issues and also just wrong. Pre-trained models based on an open dataset are a common component of many ML project repos. First and foremost it provides reproducibility of the work done which is important in scientific assessments of an algorithm, there just isn't a strong way of knowing of the results of many gpu days of processing worked as intended without a reference. 

He has a seperate fine-tuning on proprietary data that understandably he wants or needs to keep, but saying that about training on a public dataset actually flies against most standards in the industry. It just means that every repo user doesnt need to have a massive server farm to try this out.

To respond to boreas, the author has mentioned in another issue that he plans on making the AVspeech pre-trained model public but hasn't gotten around to it.
