### ISSUE TITLE
Inferencing after training wloss_hq_wav2lip_train.py

### ISSUE THREAD

**Issue by crazyxprogrammer** [primepake/wav2lip_288x288#26]
Hello，the pre-trained model named wav2lip_gan is used to inference. After my own training, there are two checkpoints：checkpoint_stepxxx and disc_checkpoint_stepxxx.
So， which checkpoint should I use in inference （with visual_quality_disc ）？

**Comment by primepake** [comment]
checkpoint_stepxxx, visual_quality_disc is a discriminator
