### ISSUE TITLE
on which dataset did you train the HD 288*288 model?

### ISSUE THREAD

**Issue by yihe1003** [primepake/wav2lip_288x288#3]
hi , thank you for your work. I want to consult about your dataset. does Lrs2 works? but the Lrs2 resolution is just 160*160.

**Comment by primepake** [comment]
My dataset is private (1080p, no noise, The expression of the speaker is very normal, not too expressive) bs 128, 4 gpus tesla p100.
 If you want, you can collect dataset from youtube and then process it 
or you can use avspeech dataset: https://looking-to-listen.github.io/avspeech/download.html

**Comment by yihe1003** [comment]
It's so nice of you ,thank you for your reply! what's more, i want to know how big is your dataset? how many speakers in total, and which language did you use. if the dataset is very large , maybe i'll drop my idea about recording videos by myself. or  can i record one person's video for a few hours to finetune the pretrained network (using avspeech) to get a better result?

**Comment by primepake** [comment]
I trained on 1080p, 10s per video, a person has multiple videos, my dataset is private because it's media production.  as you said you can train avspeech dataset to get trained model and then finetune on your video

**Comment by yihe1003** [comment]
> I trained on 1080p, 10s per video, a person has multiple videos, my dataset is private because it's media production. as you said you can train avspeech dataset to get trained model and then finetune on your video

ok， thank you for your help
