### ISSUE TITLE
avspeech train long time  Loss ~0.5

### ISSUE THREAD

**Issue by match08** [primepake/wav2lip_288x288#33]
I used avspeech data to train syncnet for 285 hours, and the training time dropped from 0.69 to 0.5. Now it has been consistently low to 0.5 for a long time. What is the reason for this. I use syncnet for avspeech syncnet_ython filtering is - 1, 1.

Evaluating for 1400 steps 0.6834709048271179

Loss: 0.5212869264862754: : 11it [00:06,  1.59it/s]
Loss: 0.516353040933609: : 11it [00:06,  1.66it/s] 
Loss: 0.506797579201785: : 11it [00:06,  1.58it/s] 
Loss: 0.5059969479387457: : 11it [00:06,  1.64it/s]
Loss: 0.5300133119929921: : 11it [00:06,  1.63it/s]
Loss: 0.5310295034538616: : 11it [00:06,  1.58it/s]
Loss: 0.517237208106301: : 11it [00:07,  1.56it/s] 
Loss: 0.534422142939134: : 11it [00:06,  1.65it/s] 
Loss: 0.5230060680346056: : 11it [00:06,  1.58it/s]
Loss: 0.5333795303648169: : 11it [00:06,  1.62it/s]
Loss: 0.5387652733109214: : 11it [00:06,  1.59it/s]
Loss: 0.5229526162147522: : 11it [00:07,  1.51it/s]
Loss: 0.5356160998344421: : 11it [00:06,  1.61it/s]
Loss: 0.5272310484539379: : 11it [00:06,  1.61it/s]
Loss: 0.5080998133529316: : 11it [00:06,  1.61it/s]
Loss: 0.5103642046451569: : 11it [00:06,  1.65it/s]
Loss: 0.5402759123932231: : 11it [00:06,  1.60it/s]
Loss: 0.5128899162465875: : 11it [00:06,  1.58it/s]
Loss: 0.5354925204407085: : 11it [00:07,  1.57it/s]
Loss: 0.5273735089735552: : 11it [00:06,  1.61it/s]
Loss: 0.5145161287351088: : 11it [00:06,  1.65it/s]
Loss: 0.5218090279535814: : 11it [00:07,  1.52it/s]
Loss: 0.5303930558941581: : 11it [00:06,  1.63it/s]
Loss: 0.5121880417520349: : 11it [00:06,  1.59it/s]
Loss: 0.5163682943040674: : 11it [00:06,  1.64it/s]
Loss: 0.5399262742562727: : 11it [00:06,  1.61it/s]
Loss: 0.5241495452143929: : 11it [00:06,  1.61it/s]
Loss: 0.5095025599002838: : 11it [00:06,  1.61it/s]
Loss: 0.5246310071511702: : 11it [00:07,  1.47it/s]
Loss: 0.5254473957148466: : 11it [00:06,  1.61it/s]
Loss: 0.5240989273244684: : 11it [00:06,  1.58it/s]
Loss: 0.5143423215909437: : 11it [00:07,  1.54it/s]
Loss: 0.5383796854452654: : 11it [00:06,  1.62it/s]
Loss: 0.5364107299934734: : 11it [00:06,  1.64it/s]
Loss: 0.535735699263486: : 11it [00:06,  1.63it/s] 
Loss: 0.5260600068352439: : 11it [00:07,  1.53it/s]
Loss: 0.5264727879654277: : 11it [00:06,  1.65it/s]
Loss: 0.5269337269392881: : 11it [00:06,  1.58it/s]
Loss: 0.5506553758274425: : 11it [00:07,  1.41it/s]
Loss: 0.5356145446950739: : 11it [00:06,  1.68it/s]
Loss: 0.53057600422339: : 11it [00:06,  1.65it/s]  
Loss: 0.5183943212032318: : 11it [00:07,  1.55it/s]
Loss: 0.5093956183303486: : 11it [00:07,  1.55it/s]
Loss: 0.5288541885939512: : 11it [00:07,  1.46it/s]
Loss: 0.5268966989083723: : 11it [00:06,  1.62it/s]
Loss: 0.5296651070768182: : 11it [00:07,  1.57it/s]
Loss: 0.5330738831650127: : 11it [00:07,  1.57it/s]
Loss: 0.5453376011414961: : 11it [00:07,  1.43it/s]
Loss: 0.5334051115946337: : 11it [00:06,  1.62it/s]
Loss: 0.5332772217013619: : 11it [00:06,  1.58it/s]
Loss: 0.5456769385121085: : 11it [00:06,  1.59it/s]
Loss: 0.5276198793541301: : 11it [00:06,  1.61it/s]
Loss: 0.5252100364728407: : 11it [00:06,  1.59it/s]
Loss: 0.547866637056524: : 11it [00:06,  1.59it/s] 
Loss: 0.534071144732562: : 11it [00:07,  1.50it/s] 
Loss: 0.5364801423116163: : 11it [00:06,  1.63it/s]
Loss: 0.5198463797569275: : 11it [00:06,  1.58it/s]
Loss: 0.5080715119838715: : 11it [00:06,  1.61it/s]
Loss: 0.5239014219154011: : 11it [00:07,  1.54it/s]
Loss: 0.5345901250839233: : 11it [00:06,  1.63it/s]
Loss: 0.5356171185320074: : 11it [00:07,  1.43it/s]
Loss: 0.5243599035523154: : 11it [00:06,  1.61it/s]
Loss: 0.5395512635057623: : 11it [00:06,  1.58it/s]
Loss: 0.526209909807552: : 11it [00:07,  1.56it/s] 
Loss: 0.5344010916623202: : 11it [00:08,  1.34it/s]
Loss: 0.5253535590388558: : 11it [00:06,  1.58it/s]
Loss: 0.5191849280487407: : 11it [00:06,  1.59it/s]
Loss: 0.5137904584407806: : 11it [00:07,  1.54it/s]
Loss: 0.5361907888542522: : 11it [00:07,  1.55it/s]
Loss: 0.5215925763953816: : 11it [00:07,  1.56it/s]
Loss: 0.5253916762091897: : 11it [00:07,  1.56it/s]
Loss: 0.5226842273365367: : 11it [00:06,  1.61it/s]
Loss: 0.5378378033638: : 11it [00:07,  1.56it/s]   
Loss: 0.5154962214556608: : 11it [00:06,  1.59it/s]
Loss: 0.5151732536879453: : 11it [00:06,  1.64it/s]
Loss: 0.5253660435026343: : 11it [00:06,  1.59it/s]
Loss: 0.5318919772451575: : 11it [00:07,  1.57it/s]
Loss: 0.5285821773789146: : 11it [00:07,  1.52it/s]
Loss: 0.5203951353376562: : 11it [00:06,  1.59it/s]
Loss: 0.5248001217842102: : 11it [00:06,  1.64it/s]
Loss: 0.5474389899860729: : 11it [00:06,  1.59it/s]
Loss: 0.5239813354882327: : 11it [00:06,  1.59it/s]
Loss: 0.510086715221405: : 11it [00:07,  1.53it/s] 
Loss: 0.5268921526995572: : 11it [00:06,  1.59it/s]
Loss: 0.5242643247951161: : 11it [00:08,  1.35it/s]
Loss: 0.5328544540838762: : 11it [00:06,  1.61it/s]
Loss: 0.5278959978710521: : 11it [00:07,  1.51it/s]
Loss: 0.5087671984325756: : 11it [00:06,  1.64it/s]
Loss: 0.5189093026247892: : 11it [00:06,  1.58it/s]
Loss: 0.5501838326454163: : 11it [00:08,  1.37it/s]
Loss: 0.5115621387958527: : 11it [00:07,  1.55it/s]
Loss: 0.5253327245062048: : 11it [00:06,  1.61it/s]
Loss: 0.5272630588574843: : 11it [00:06,  1.61it/s]
Loss: 0.5148500204086304: : 11it [00:07,  1.54it/s]
Loss: 0.5340689122676849: : 11it [00:06,  1.60it/s]
Loss: 0.5341784683140841: : 11it [00:07,  1.54it/s]
Loss: 0.521747889843854: : 11it [00:06,  1.62it/s]
Loss: 0.5119168541648171: : 11it [00:06,  1.63it/s]
Loss: 0.5264650989662517: : 11it [00:07,  1.54it/s]
Loss: 0.5414948653091084: : 11it [00:06,  1.58it/s]
Loss: 0.5448070005937056: : 11it [00:06,  1.63it/s]
Loss: 0.510159890760075: : 11it [00:06,  1.59it/s] 
Loss: 0.5324155363169584: : 11it [00:07,  1.57it/s]
Loss: 0.5363136529922485: : 11it [00:06,  1.59it/s]
Loss: 0.527454985813661: : 11it [00:06,  1.61it/s] 
Loss: 0.5277877937663685: : 11it [00:07,  1.41it/s]
Loss: 0.524616306478327: : 11it [00:06,  1.58it/s] 
Loss: 0.5203610306436365: : 11it [00:07,  1.55it/s]
Loss: 0.5298510220917788: : 11it [00:07,  1.57it/s]
Loss: 0.5173395330255682: : 11it [00:07,  1.56it/s]
Loss: 0.533916874365373: : 11it [00:06,  1.66it/s] 
Loss: 0.5159734921021895: : 11it [00:06,  1.63it/s]
Loss: 0.5441486456177451: : 11it [00:06,  1.60it/s]
Loss: 0.5260709740898826: : 11it [00:06,  1.64it/s]
Loss: 0.5441469766876914: : 11it [00:06,  1.60it/s]
Loss: 0.5286740227179094: : 11it [00:06,  1.65it/s]
Loss: 0.5092522854154761: : 11it [00:06,  1.58it/s]
Loss: 0.512138466943394: : 11it [00:06,  1.61it/s] 
Loss: 0.5216747386889025: : 11it [00:07,  1.57it/s]
Loss: 0.5291207080537622: : 11it [00:07,  1.49it/s]
Loss: 0.5329246493903074: : 11it [00:06,  1.61it/s]
Loss: 0.5120911191810261: : 11it [00:07,  1.55it/s]
Loss: 0.5228245149959218: : 11it [00:07,  1.57it/s]
Loss: 0.5253384844823317: : 11it [00:06,  1.64it/s]
Loss: 0.5360355079174042: : 11it [00:07,  1.52it/s]
Loss: 0.5080934898419813: : 11it [00:06,  1.57it/s]
Loss: 0.5472726388411089: : 11it [00:07,  1.53it/s]
Loss: 0.5124477256428112: : 11it [00:07,  1.52it/s]
Loss: 0.5321660935878754: : 11it [00:06,  1.58it/s]
Loss: 0.5292721851305529: : 11it [00:06,  1.59it/s]
Loss: 0.5342415164817463: : 11it [00:06,  1.64it/s]
Loss: 0.5322149070826444: : 11it [00:07,  1.56it/s]
Loss: 0.5233434005217119: : 11it [00:06,  1.60it/s]
Loss: 0.5123658369887959: : 11it [00:07,  1.53it/s]
Loss: 0.5206985040144487: : 11it [00:07,  1.41it/s]
Loss: 0.5344440151344646: : 11it [00:06,  1.63it/s]
Loss: 0.5306854437698018: : 11it [00:06,  1.57it/s]
Loss: 0.5189629088748585: : 11it [00:06,  1.62it/s]
Loss: 0.551388068632646: : 11it [00:07,  1.53it/s] 
Loss: 0.5213939059864391: : 11it [00:06,  1.61it/s]
Loss: 0.5267486572265625: : 11it [00:06,  1.61it/s]
Loss: 0.5126107416369698: : 11it [00:06,  1.64it/s]
Loss: 0.5210787735202096: : 11it [00:07,  1.52it/s]
Loss: 0.5091477849266746: : 11it [00:06,  1.62it/s]
Loss: 0.5227019597183574: : 11it [00:07,  1.50it/s]
Loss: 0.5210425935008309: : 11it [00:06,  1.59it/s]
Loss: 0.537912601774389: : 11it [00:07,  1.52it/s] 
Loss: 0.5248223380608992: : 11it [00:07,  1.57it/s]
Loss: 0.517209218306975: : 11it [00:07,  1.44it/s] 
Loss: 0.505943544886329: : 11it [00:06,  1.61it/s] 
Loss: 0.5258536582643335: : 11it [00:06,  1.59it/s]
Loss: 0.5366070893677798: : 11it [00:06,  1.63it/s]
Loss: 0.5362473644993522: : 11it [00:07,  1.54it/s]

**Comment by primepake** [comment]
did you filter with syncnet_python correctly?
because the size of input syncnet_python isn't the same with wav2lip input

**Comment by match08** [comment]
> did you filter with syncnet_python correctly? because the size of input syncnet_python isn't the same with wav2lip input

input img_size ?

**Comment by primepake** [comment]
syncnet_python use an image with expand face not just a face size
