### ISSUE TITLE
Can you provide AVSpeech dataset? I can't download it

### ISSUE THREAD

**Issue by OldSixOne** [primepake/wav2lip_288x288#41]
Can you provide AVSpeech dataset? I can't download it

**Comment by primepake** [comment]
you can use youtube-dl or pytube to download with youtube_id from https://looking-to-listen.github.io/avspeech/download.html

**Comment by OldSixOne** [comment]
Because of the network, I will not be able to download，So I asked if you could provide this data set。

**Comment by MaxMax2016** [comment]
https://hyper.ai/datasets/8754 it is too big
