### ISSUE TITLE
I use LRS2 dataset to train the wav2lip model, but the moving of mouth shape is too small

### ISSUE THREAD

**Issue by yangmao123** [primepake/wav2lip_288x288#42]
I tried the author's wav2lip training pipeline with the whole LRS2 datasets as the author did, but I got a very small mouth moving. In contrast, I download the author's wav2lip_gan.pth and test the results, it has a regular mouth moving and it's bigger than mine.
So I want to ask you if you have any suggestion about this question.

Looking forward to your reply, thanks!

**Comment by MaxMax2016** [comment]
i meet the same problem

**Comment by primepake** [comment]
it seems like the author train with multiple resource, also wav2lip depends on your mouth shape to predict the size of open mouth

**Comment by zhangziwenHIT** [comment]
> i meet the same problem
Have u sove this problem?
