### ISSUE TITLE
have you tried to finetune into a single person model?

### ISSUE THREAD

**Issue by Zhang-Xiaoyi** [primepake/wav2lip_288x288#45]
I want to build a personalized wav2lip but finetuning it to a single person (5 min video) cannot get results. I am wondering if I use longer video, maybe 1 hour, I can get better results. Just want to see if you have any experience.

**Comment by primepake** [comment]
wav2lip needs more than 5 minutes, 80 minutes is good for

**Comment by xuduo18311199384** [comment]
Have you ever built a well personalized wav2lip? When i fine-tune a 3 min video, i get a bad results. Do you have a good result by using long video or any train skills for short video? Can you recommend some projects for personalized talker? @Zhang-Xiaoyi
