### ISSUE TITLE
run color_syncnet_train.py have a error

### ISSUE THREAD

**Issue by hupu1dong** [primepake/wav2lip_288x288#48]
my command:
`python color_syncnet_train.py  --data_root /home//dataset/myvideo_dataset/preprocess  --checkpoint_dir /home//vir-person/wav2lip_288x288/myvideo_chekpoint`

and then error:
```
Loss: 1.1169637313910894: : 14it [01:43,  2.70s/it]/pytorch/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [46,0,0] Assertion `input >= 0. && input <= 1.` failed.
Loss: 1.1169637313910894: : 14it [01:44,  7.47s/it]
Traceback (most recent call last):
  File "color_syncnet_train.py", line 279, in <module>
    nepochs=hparams.nepochs)
  File "color_syncnet_train.py", line 161, in train
    loss = cosine_loss(a, v, y)
  File "color_syncnet_train.py", line 136, in cosine_loss
    loss = logloss(d.unsqueeze(1), y)
  File "/root/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 512, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/root/anaconda3/envs/wav2lip/lib/python3.6/site-packages/torch/nn/functional.py", line 2113, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: device-side assert triggered
```

**Comment by hupu1dong** [comment]
I found that this training can be run normally without using LeakyReLU, and I believe it is caused by inconsistent data shapes during computation loss caused by LeakyReLU

**Comment by hupu1dong** [comment]
Have you verified the author before uploading the code @primepake

**Comment by Zgj2005** [comment]
可是兄弟, color_syncnet_train.py 似乎执行不到 LeakyReLU, 虽然有问题, 但是应该不是这个问题

**Comment by carter54** [comment]
It's due to PReLU, PReLU could have negative output to audio vector and face vector, and the cosine_similarity will have negative value.
 @primepake Could you share your method to solve this problem? 
I saw you mentioned that using BCELogicLoss would have other problem, I think the training loss will stay near 0.6...
Did you still use cosine_loss in color_syncnet_train.py or change to other loss function?

Thanks in advance!

**Comment by DogeFlow** [comment]
For the same question, the author mentioned the use of BCELogicLoss, but in the subsequent answer, he suggested not to use it. If you do not use BCELogicLoss, you will not be able to train. So what is the correct way to deal with it? @primepake

**Comment by primepake** [comment]
I recommend you shouldn't you BCELogicLoss, this not correct. You should apply ReLU in the last layer to get the value in range [0,1]

**Comment by DogeFlow** [comment]
> I recommend you shouldn't you BCELogicLoss, this not correct. You should apply ReLU in the last layer to get the value in range [0,1]

Thank you very much, it worked

**Comment by xiedongmingming** [comment]
> > I recommend you shouldn't you BCELogicLoss, this not correct. You should apply ReLU in the last layer to get the value in range [0,1]
> 
> Thank you very much, it worked

Could you share your method to solve this problem?
