### ISSUE TITLE
about the PRelu & LeakyRelu improvement

### ISSUE THREAD

**Issue by weizmann** [primepake/wav2lip_288x288#50]
Thanks for your great work!

I have used the original wav2lip model to process wild video dubbing, and found there will be some abnormal color in the mouth occasional.

I think the reason is the original wav2lip model lacks proper softmax/relu process when handling color generation.

I read from your README and found that the 288x288 model used more powerful ReLU to process the convnet.

I have 2 questions about the improvement:
Q1: Why did you choose to update the PRelu & LeakyRelu? can you give me some typical scenarios when PRelu/LeakyRelu works better?
Q2: Will 288x288 model eliminates the abnormal color in the mouth?

Some bad cases in original Wav2Lip model:

![image](https://user-images.githubusercontent.com/2306111/233961740-3b2434a2-e64c-4610-9d68-722a09daafe7.png)

![image](https://user-images.githubusercontent.com/2306111/233961504-4811a686-6f7a-464d-8abd-f03d76bf4c15.png)

![image](https://user-images.githubusercontent.com/2306111/233960559-6723b35b-3469-4932-b7b3-f384554630ad.png)

**Comment by weizmann** [comment]
It will be better to give us some effect comparison videos ☺️

**Comment by primepake** [comment]
q1: I chosen these activations because I rearange of scale, [-1,1] instead of [0,1] by following: https://github.com/soumith/ganhacks
q2: wav2lip 288x288 is just the upscale version of the original for the better resolution.
