### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by shenriver** [primepake/wav2lip_288x288#51]
Hello, I have looked at all the issues, but there are many confusion. For example, some say they need to modify the leakyrelu loss, and I want to prepare my own dataset training. May I ask if this code is complete? Can I simply not modify it?

**Comment by primepake** [comment]
will update the code and release soon

**Comment by Kafeyun** [comment]
> will update the code and release soon

thanks for your working!

**Comment by carter54** [comment]
any timeline to release the code? @primepake 
Thx~
