### ISSUE TITLE
Number of usable Avspeech videos.

### ISSUE THREAD

**Issue by Bebaam** [primepake/wav2lip_288x288#52]
Hey,

I have a question regarding the number of videos which fullfill the conditions for preprocessing mentioned in the other issues (confidence 6-9 and offset between -3 and 3). How many files remain after preprocessing the AvSpeech dataset? When I try with a few thousand, only 1-2% are usable. At the end I would only have around 25-50k files (Which may not be enough).

Did I do anything wrong preprocessing or are nearly all the videos just not in sync? How many files did you get after preprocessing the whole dataset?

Thanks in advance.

**Comment by primepake** [comment]
the pretrained syncnet is not good on high quality of dataset

**Comment by akshatgarg99** [comment]
so how should one proceed? Also do they not crop and resize it to 244 resolution?
