### ISSUE TITLE
sync loss keep getting bigger

### ISSUE THREAD

**Issue by DogeFlow** [primepake/wav2lip_288x288#55]
Hello, I am using hq_wav2lip_train.py for training, and the expert loss has dropped to 0.2 before. At the beginning, the sync loss was always 0, and the percep loss was around 0.69. After training for a period of time, the sync loss began to gradually increase, and the percep loss also increased, but the fake and real loss continued to decrease. Now sync loss has been increased to 20, percep loss is 1.99 .I don't know what went wrong, what should the correct loss curve look like?

**Comment by jinyugy21** [comment]
I'm having the same problem as you, have you solved it?

**Comment by primepake** [comment]
Hi, thanks for interesting. The most importance thing is dataset, do you check the dataset is preprocessed in the correct way?
