### ISSUE TITLE
What is the inference time compared with Wav2Lip?

### ISSUE THREAD

**Issue by forest520** [primepake/wav2lip_288x288#6]
For example, 2x inference time?
Thanks!

**Comment by primepake** [comment]
1080p resolution in our practice

**Comment by forest520** [comment]
> 1080p resolution in our practice

sure, could it be real time 1080P&30fps on GPU such as V100?

**Comment by primepake** [comment]
no, you can use wav2lip, it can run in real-time if you save face result detection in your DB like as a cache
