### ISSUE TITLE
Run preprocess.py 

### ISSUE THREAD

**Issue by saiyi123** [primepake/wav2lip_288x288#62]
File "preprocess.py", line 85, in mp_handler
    process_video_file(vfile, args, gpu_id)
  File "preprocess.py", line 50, in process_video_file
    dirname = vfile.split('/')[-2]
IndexError: list index out of range

**Comment by sth0409** [comment]
应该是路径的问题吧 可以检查一下

**Comment by saiyi123** [comment]
Thank you very much. It is indeed a path related issue, and the Windows system has encountered quite a few problems running these things.
