### ISSUE TITLE
How to resolve " the shape in current model is torch.Size([512, 512, 3, 3])"

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [primepake/wav2lip_288x288#64]
![image](https://github.com/primepake/wav2lip_288x288/assets/87591236/1cc3c688-23e3-4d40-9420-36ee5057de06)
I have some problems with this.
All parameters are default values, how to resolve this error。

**Comment by OliverAAAAA** [comment]
me too, how to resolve it???  help !!!
