### ISSUE TITLE
训练后的模型推理嘴巴不动是哪里出问题了呢

### ISSUE THREAD

**Issue by A-ka-duo-jiu-o** [primepake/wav2lip_288x288#66]
你好，训练后的模型推理嘴巴不动是哪里出问题了呢，是鉴别器收敛不到位还是生成模型没训练好。
@primepake

**Comment by xiedongmingming** [comment]
@A-ka-duo-jiu-o 你用源代码能正常训练？

Traceback (most recent call last):
  File "G:/software/pycharm/PyCharm 2023.1.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "G:\software\pycharm\PyCharm 2023.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\workspace\github\wav2lip_288x288\color_syncnet_train.py", line 418, in <module>
    train(
  File "E:\workspace\github\wav2lip_288x288\color_syncnet_train.py", line 250, in train
    loss = cosine_loss(a, v, y)
  File "E:\workspace\github\wav2lip_288x288\color_syncnet_train.py", line 210, in cosine_loss
    loss = logloss(d.unsqueeze(1), y)
  File "D:\software\anaconda\envs\wav2lip\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\software\anaconda\envs\wav2lip\lib\site-packages\torch\nn\modules\loss.py", line 619, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "D:\software\anaconda\envs\wav2lip\lib\site-packages\torch\nn\functional.py", line 3098, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

python-BaseException

这个错误你是怎么解决的？

**Comment by saiyi123** [comment]
> @A-ka-duo-jiu-o 你用源代码能正常训练？
> 
> Traceback (most recent call last): File "G:/software/pycharm/PyCharm 2023.1.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec pydev_imports.execfile(file, globals, locals) # execute the script File "G:\software\pycharm\PyCharm 2023.1.2\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "E:\workspace\github\wav2lip_288x288\color_syncnet_train.py", line 418, in train( File "E:\workspace\github\wav2lip_288x288\color_syncnet_train.py", line 250, in train loss = cosine_loss(a, v, y) File "E:\workspace\github\wav2lip_288x288\color_syncnet_train.py", line 210, in cosine_loss loss = logloss(d.unsqueeze(1), y) File "D:\software\anaconda\envs\wav2lip\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "D:\software\anaconda\envs\wav2lip\lib\site-packages\torch\nn\modules\loss.py", line 619, in forward return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction) File "D:\software\anaconda\envs\wav2lip\lib\site-packages\torch\nn\functional.py", line 3098, in binary_cross_entropy return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum) RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> python-BaseException
> 
> 这个错误你是怎么解决的？

请参考这个地方
#60

**Comment by xiedongmingming** [comment]
感谢感谢！

```
wav2lip_288x288/models/conv2.py

 self.act = nn.PReLU() -> self.act = nn.ReLU()
```
 
 
 就这一个地方吗？还有别的吗？我看作者提到了BCELogicLoss的问题，但没看明白
 #48

**Comment by saiyi123** [comment]
> 感谢感谢！
> 
> ```
> wav2lip_288x288/models/conv2.py
> 
>  self.act = nn.PReLU() -> self.act = nn.ReLU()
> ```
> 
> 就这一个地方吗？还有别的吗？我看作者提到了BCELogicLoss的问题，但没看明白 #48

你改这一个地方就可以训练了，那个跟这个没有关系。

**Comment by xiedongmingming** [comment]
> 

大佬，你那边修改模型结构了吗？我这边训练损失一直降不下去，群里有人说这个模型有问题

**Comment by xiedongmingming** [comment]
> 



> > 感谢感谢！
> > ```
> > wav2lip_288x288/models/conv2.py
> > 
> >  self.act = nn.PReLU() -> self.act = nn.ReLU()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就这一个地方吗？还有别的吗？我看作者提到了BCELogicLoss的问题，但没看明白 #48
> 
> 你改这一个地方就可以训练了，那个跟这个没有关系。

大佬，你那边修改模型结构了吗？我这边训练损失一直降不下去，群里有人说这个模型有问题

**Comment by fordeep3d** [comment]
> > 
> 
> > > 感谢感谢！
> > > ```
> > > wav2lip_288x288/models/conv2.py
> > > 
> > >  self.act = nn.PReLU() -> self.act = nn.ReLU()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 就这一个地方吗？还有别的吗？我看作者提到了BCELogicLoss的问题，但没看明白 #48
> > 
> > 
> > 你改这一个地方就可以训练了，那个跟这个没有关系。
> 
> 大佬，你那边修改模型结构了吗？我这边训练损失一直降不下去，群里有人说这个模型有问题

您好，您用这个288的训练下去了吗，从开始的口型鉴别训练损失就不下降

**Comment by shengzewen** [comment]
推理的时候报错ValueError: Face not detected! Ensure the video contains a face in all the frames，您有遇到过这个问题吗

**Comment by kunyao2015** [comment]
@A-ka-duo-jiu-o  你的问题解决了吗，什么原因呢
