### ISSUE TITLE
Train the expert discriminator to report errors

### ISSUE THREAD

**Issue by shengzewen** [primepake/wav2lip_288x288#68]
Run color_syncnet_train.py on the server, and in the middle of running, an error occurs:   
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
What is the reason?

**Comment by shengzewen** [comment]
我更改了PReLU为ReLU后，虽然color_syncnet_train.py能训练起来，但是损失值一直在0.7左右降不下去，这是为什么

**Comment by fordeep3d** [comment]
> 我更改了PReLU为ReLU后，虽然color_syncnet_train.py能训练起来，但是损失值一直在0.7左右降不下去，这是为什么

我也是降不下去，模型结构有问题吗

**Comment by shengzewen** [comment]
> 

很有可能是因为数据预处理出问题了，你可以看看 #21 。我按照作者的要求处理后，损失值下降了

**Comment by fordeep3d** [comment]
> > 
> 
> 很有可能是因为数据预处理出问题了，你可以看看 #21 。我按照作者的要求处理后，损失值下降了

非常感谢
