### ISSUE TITLE
wav2lip 288x288 color of the lips overflows

### ISSUE THREAD

**Issue by match08** [primepake/wav2lip_288x288#70]
My  val  wav2lip 288x288 demo:
https://github-production-user-asset-6210df.s3.amazonaws.com/616730/261982050-82b7379b-295c-4f89-a3c8-0c372299535d.mp4

There will be solid color blocks of black and white outside, as if the color has been lost. And the color of the lips overflows

![samples_step001521000_1546223_55b49d51e5cbfa7689ed](https://github.com/primepake/wav2lip_288x288/assets/616730/57720470-b6d0-4b94-904a-0b13821f567e)

**Comment by ngbien83** [comment]
Can you share the checkpoint?
