### ISSUE TITLE
损失值一直下降不下来

### ISSUE THREAD

**Issue by shengzewen** [primepake/wav2lip_288x288#73]
感谢作者的贡献！我想问下训练唇形生成器的时候，损失值一直在1.02-1.15之间浮动。想问下有什么方法可以让损失值下降吗，例如增加多少量的数据集？更改网络层？还是修改什么超参数 @primepake 
![image](https://github.com/primepake/wav2lip_288x288/assets/48091887/2ad06196-e448-4f8d-83ad-de214f23c784)

**Comment by MGeorge01** [comment]
你的判别器是自己训练的吗？训练判别器的时候loss降到了多少

**Comment by shengzewen** [comment]
> 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少

0.2左右

**Comment by MGeorge01** [comment]
> > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> 
> 0.2左右

我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？

**Comment by shengzewen** [comment]
> > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > 
> > 
> > 0.2左右
> 
> 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？

自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU

**Comment by MGeorge01** [comment]
> > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > 
> > > 
> > > 0.2左右
> > 
> > 
> > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> 
> 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU

我改了学习率，现在开始降了，但是降的很慢

**Comment by MGeorge01** [comment]
> > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > 
> > > 
> > > 0.2左右
> > 
> > 
> > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> 
> 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU

你是说torch里的conv2.py吗？

**Comment by MGeorge01** [comment]
> > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > 
> > > 
> > > 0.2左右
> > 
> > 
> > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> 
> 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU

我找不到你说的这个conv2.py在哪，在哪里啊

**Comment by shengzewen** [comment]
> > > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > > 
> > > > 
> > > > 0.2左右
> > > 
> > > 
> > > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> > 
> > 
> > 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU
> 
> 我找不到你说的这个conv2.py在哪，在哪里啊

models里的conv2.py，前提是你下载的wav2lip_288x288源码

**Comment by MGeorge01** [comment]
> > > > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > > > 
> > > > > 
> > > > > 0.2左右
> > > > 
> > > > 
> > > > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> > > 
> > > 
> > > 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU
> > 
> > 
> > 我找不到你说的这个conv2.py在哪，在哪里啊
> 
> models里的conv2.py，前提是你下载的wav2lip_288x288源码

感谢，找到了，两个PReLU都改吗？

**Comment by shengzewen** [comment]
> 

改第一个就行，PReLU适合较大的数据集

**Comment by shengzewen** [comment]
> > > > > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > > > > 
> > > > > > 
> > > > > > 0.2左右
> > > > > 
> > > > > 
> > > > > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> > > > 
> > > > 
> > > > 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU
> > > 
> > > 
> > > 我找不到你说的这个conv2.py在哪，在哪里啊
> > 
> > 
> > models里的conv2.py，前提是你下载的wav2lip_288x288源码
> 
> 感谢，找到了，两个PReLU都改吗？

改第一个就行，PReLU适合较大的数据集

**Comment by MGeorge01** [comment]
> > > > > > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > > > > > 
> > > > > > > 
> > > > > > > 0.2左右
> > > > > > 
> > > > > > 
> > > > > > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> > > > > 
> > > > > 
> > > > > 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU
> > > > 
> > > > 
> > > > 我找不到你说的这个conv2.py在哪，在哪里啊
> > > 
> > > 
> > > models里的conv2.py，前提是你下载的wav2lip_288x288源码
> > 
> > 
> > 感谢，找到了，两个PReLU都改吗？
> 
> 改第一个就行，PReLU适合较大的数据集

我的数据集就很大，接近100G

**Comment by shengzewen** [comment]
> > > > > > > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 0.2左右
> > > > > > > 
> > > > > > > 
> > > > > > > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> > > > > > 
> > > > > > 
> > > > > > 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU
> > > > > 
> > > > > 
> > > > > 我找不到你说的这个conv2.py在哪，在哪里啊
> > > > 
> > > > 
> > > > models里的conv2.py，前提是你下载的wav2lip_288x288源码
> > > 
> > > 
> > > 感谢，找到了，两个PReLU都改吗？
> > 
> > 
> > 改第一个就行，PReLU适合较大的数据集
> 
> 我的数据集就很大，接近100G

那就是数据集的问题了，你看看 #21

**Comment by MGeorge01** [comment]
> > > > > > > > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 0.2左右
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU
> > > > > > 
> > > > > > 
> > > > > > 我找不到你说的这个conv2.py在哪，在哪里啊
> > > > > 
> > > > > 
> > > > > models里的conv2.py，前提是你下载的wav2lip_288x288源码
> > > > 
> > > > 
> > > > 感谢，找到了，两个PReLU都改吗？
> > > 
> > > 
> > > 改第一个就行，PReLU适合较大的数据集
> > 
> > 
> > 我的数据集就很大，接近100G
> 
> 那就是数据集的问题了，你看看 #21

感谢，降下来了

**Comment by SuperGoodGame** [comment]
请问你用[sync](https://github.com/joonson/syncnet_python) 这里面的代码了吗，
如果有，请问你如何使用它
如果没有，请问你对数据集做了那些修改，（转换25帧，剪切视频，以及其他）
十分感谢回复

**Comment by Yyyyyyxh** [comment]
> > > > > > > > > > > 你的判别器是自己训练的吗？训练判别器的时候loss降到了多少
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 0.2左右
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我判别器的Loss都降不下来，一直在0.58，你用的自己的数据集吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 自己的数据集，降不下来你可以把conv2.py里的PReLU改成ReLU
> > > > > > > 
> > > > > > > 
> > > > > > > 我找不到你说的这个conv2.py在哪，在哪里啊
> > > > > > 
> > > > > > 
> > > > > > models里的conv2.py，前提是你下载的wav2lip_288x288源码
> > > > > 
> > > > > 
> > > > > 感谢，找到了，两个PReLU都改吗？
> > > > 
> > > > 
> > > > 改第一个就行，PReLU适合较大的数据集
> > > 
> > > 
> > > 我的数据集就很大，接近100G
> > 
> > 
> > 那就是数据集的问题了，你看看 #21
> 
> 感谢，降下来了

请问怎么降下来的，我跟您遇到了同样的问题

**Comment by aishoot** [comment]
the same issue

**Comment by drakitLiu** [comment]
> PReLU
敢问 您这自己的数据集？1.py  loss下降到了多少?
我一直停留在专家判别器  ~0.45
