### ISSUE TITLE
May I ask how you use syncnet_ Python batch filters datasets within the range of [-1,1], and I have thousands of videos

### ISSUE THREAD

**Issue by kike-0304** [primepake/wav2lip_288x288#75]
May I ask how you use syncnet_ Python batch filters datasets within the range of [-1,1], and I have thousands of videos

**Comment by SuperGoodGame** [comment]
Hello ,i have the same problem ,and do you know the dataset standard?

**Comment by SuperGoodGame** [comment]
#60  you can try it to deal with it

**Comment by SuperGoodGame** [comment]
hi do you deal with it ，i have the same problem ，how to use it

**Comment by primepake** [comment]
https://github.com/joonson/syncnet_python/blob/master/run_syncnet.py
