### ISSUE TITLE
dataset standard

### ISSUE THREAD

**Issue by SuperGoodGame** [primepake/wav2lip_288x288#77]
> Traceback (most recent call last):
>   File "color_syncnet_train.py", line 279, in <module>
>     nepochs=hparams.nepochs)
>   File "color_syncnet_train.py", line 162, in train
>     loss.backward()
>   File "/home/jiahuaw/anaconda3/envs/wav2lip/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/jiahuaw/anaconda3/envs/wav2lip/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: CUDA error: device-side assert triggered
> /pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [8,0,0] Assertion `input_val >= zero && input_val <= one` failed.
i think my dataset have some problem.And i don.t know how to prepare.
i just preprocess it with the orignal wav2lip program
我只用了原版wav2lip 的数据处理，不知道怎么再对数据集处理，有人知道数据集需要的标准是什么吗

**Comment by SuperGoodGame** [comment]
我看了cleardata.py 上面好像是需要对帧数有要求，有人知道标准吗，十分感谢

**Comment by Arvin-keke** [comment]
25帧

**Comment by SuperGoodGame** [comment]
我的数据确实是25帧，也都有人脸，有人遇到过这个报错吗
mydataset seems match the standard ，have someone meet this error

**Comment by SuperGoodGame** [comment]
the problem has been soloved
 the method #60
