### ISSUE TITLE
how you use syncnet_ Python

### ISSUE THREAD

**Issue by SuperGoodGame** [primepake/wav2lip_288x288#79]
i dont know how to use use syncnet_ Python batch f**ilters datasets within the range of [-1,1]**with thousands video,the https://github.com/joonson/syncnet_python seem not to mention it.

**Comment by fjesikfjdskl** [comment]
The same question！！！

**Comment by primepake** [comment]
you should try this pipe_line: https://github.com/joonson/syncnet_python/blob/master/run_syncnet.py
then it can return the offset and the offset should be in [-1,1]

**Comment by einsqing** [comment]
> you should try this pipe_line: https://github.com/joonson/syncnet_python/blob/master/run_syncnet.py then it can return the offset and the offset should be in [-1,1]

syncnet_ Python
Is it Chinese or English?

**Comment by primepake** [comment]
you can check the data they've trained on
