### ISSUE TITLE
This is a great job, thank you to the author.  A high-quality dataset will make training simple and easy to succeed.

### ISSUE THREAD

**Issue by langzizhixin** [primepake/wav2lip_288x288#80]
This is a great job, thank you to the author.
A high-quality dataset will make training simple and easy to succeed.
![f971d70d8e4113780f7c199135cdfd2](https://github.com/primepake/wav2lip_288x288/assets/74521932/c6fa80d4-0255-404b-9b7b-223b2eca0491)

**Comment by Amber-Believe** [comment]
Hi! Do you use Chinese data set?  I would like to ask you a question: I use Chinese data set to train expert lip-sync discriminator, and the train loss remains at 0.69.  Do you have such a situation
