### ISSUE TITLE
What causes black spots on the face of images generated by models trained on my customer dataset？

### ISSUE THREAD

**Issue by WYanNuo** [primepake/wav2lip_288x288#84]
![图片](https://github.com/primepake/wav2lip_288x288/assets/47735862/76285caf-a761-4e7a-886a-2338a0dda6b6)

**Comment by primepake** [comment]
this is artifacts it's normal when you're training gans

**Comment by WYanNuo** [comment]
like this
![Uploading 图片.png…]()

**Comment by Mxwgreat** [comment]
@WYanNuo Hello，I also encountered a similar problem. Have you solved it？
