### ISSUE TITLE
SAM-UNet

### ISSUE THREAD

**Issue by kenwaytis** [primepake/wav2lip_288x288#86]
How do I use the new SAM-UNet? Do I just need to replace the import statement in train code with the Wav2Lip_SAM?

**Comment by primepake** [comment]
I will release in the end of this week

**Comment by primepake** [comment]
I just added with this commit 
https://github.com/primepake/wav2lip_288x288/commit/91044317bf14978f4b86c4793bcb4a7e0a82b6cd
