### ISSUE TITLE
Hello, can I use an 80-minute video of a single person to train the bottom model, and then use another person for 5 minutes of fine-tuning?

### ISSUE THREAD

**Issue by einsqing** [primepake/wav2lip_288x288#87]
Hello, can I use an 80-minute video of a single person to train the bottom model, and then use another person for 5 minutes of fine-tuning? @primepake

**Comment by primepake** [comment]
in my experience, a single person needs at least 60 minutes to train to get good result

**Comment by einsqing** [comment]
> in my experience, a single person needs at least 60 minutes to train to get good result

After training 60 minutes of a single person video, can another person fine-tune 5 minutes of good results?

**Comment by primepake** [comment]
I'm not sure! I think if you want to finetune you will need a general model can be trained on large data then you can do that

**Comment by Nyquist0** [comment]
> Hello, can I use an 80-minute video of a single person to train the bottom model, and then use another person for 5 minutes of fine-tuning? @primepake

Hi @einsqing, may I ask did you try training a person-specific model with a single person video from scratch? Did you get good results finally?
