### ISSUE TITLE
modification about Wasserstein

### ISSUE THREAD

**Issue by yihe1003** [primepake/wav2lip_288x288#9]
hi sorry to troble again, 
I noticed that it is mentioned some modification about  Wasserstein compared to the original version . As i know， if use Wasserstein, the last layer sigmoid of discriminator needs to be removed , and each time the parameter of discriminator is updated, we should clip them to a constant and so on.
But i can find these modification in the code. is there misunderstanding about Wasserstein by me? looking forward to your help

**Comment by primepake** [comment]
Hi, there.
I have a plan to provide this implementation but not for this time.

**Comment by yihe1003** [comment]
when i train the sync net with avspeech, i found the loss dropped very slow. it takes 3days for the loss drop from 0.69 to 0.65。。
I tried to change the lr to 1e-5; increase the batch size to 128; even change the PRELU back to relu. but none of this trick works.
Did you ever met this issue? or would you please kindly give some suggestion? Thank you!
