### ISSUE TITLE
Latest updates

### ISSUE THREAD

**Issue by ChengsongLu** [primepake/wav2lip_288x288#90]
Is the latest update complete, and does the conv2d code need to be updated as well?   o.0?

**Comment by primepake** [comment]
solved it https://github.com/primepake/wav2lip_288x288/tree/e0d86abd8ca1756fd0ffe4e5f7d68cc1d33e4a54

**Comment by ChengsongLu** [comment]
> solved it https://github.com/primepake/wav2lip_288x288/tree/e0d86abd8ca1756fd0ffe4e5f7d68cc1d33e4a54

Cheers! Thanks for such great contributions!

**Comment by ChengsongLu** [comment]
BTW, is this new conv2d module works for the latest 512 models only or it is general for every ones?

I mean, is this new conv2d suitable for the syncnet288 as well?
