### ISSUE TITLE
How many steps for SyncNet to converge?

### ISSUE THREAD

**Issue by Nyquist0** [primepake/wav2lip_288x288#97]
Hi. Thanks for sharing your adjustment based on the official Wav2lip. Many adjustments are really valuable. Appreciate that.

I am using the **offcial LRS2 dataset** for training, and currently stuck on the SyncNet training.
The LR is 1e-4, and BS is 64. I did not change other settings of your config.
And now the Loss is stuck in 0.69, which shows that it does not have any ability of distinguish if the video is synced and shows no clue to converge. It is trained for 82k steps already.

So I would like to ask how many steps for your training beginning to converge?
Do you think I should keep waiting?

**Comment by primepake** [comment]
there are many issues related about this. You can check one here: https://github.com/primepake/wav2lip_288x288/issues/81

**Comment by aishoot** [comment]
> Hi. Thanks for sharing your adjustment based on the official Wav2lip. Many adjustments are really valuable. Appreciate that.
> 
> I am using the **offcial LRS2 dataset** for training, and currently stuck on the SyncNet training. The LR is 1e-4, and BS is 64. I did not change other settings of your config. And now the Loss is stuck in 0.69, which shows that it does not have any ability of distinguish if the video is synced and shows no clue to converge. It is trained for 82k steps already.
> 
> So I would like to ask how many steps for your training beginning to converge? Do you think I should keep waiting?

The same problem.

**Comment by 1129571** [comment]
> Hi. Thanks for sharing your adjustment based on the official Wav2lip. Many adjustments are really valuable. Appreciate that.你好。感谢您分享您基于官方 Wav2lip 的调整。许多调整真的很有价值。欣赏这一点。
> 
> I am using the **offcial LRS2 dataset** for training, and currently stuck on the SyncNet training.我正在使用官方 LRS2 数据集进行训练，目前停留在 SyncNet 训练上。 The LR is 1e-4, and BS is 64. I did not change other settings of your config.LR 为 1e-4，BS 为 64。我没有更改您配置的其他设置。 And now the Loss is stuck in 0.69, which shows that it does not have any ability of distinguish if the video is synced and shows no clue to converge. It is trained for 82k steps already.而现在 Loss 卡在 0.69，这表明它没有任何区分视频是否同步的能力，也没有显示收敛的线索。它已经训练了 82k 步。
> 
> So I would like to ask how many steps for your training beginning to converge?所以我想问一下，你的训练开始收敛了多少步？ Do you think I should keep waiting?你认为我应该继续等待吗？

Hello, I also encountered this issue using LRS2. How did you solve it
